FROM node:20-bullseye

WORKDIR /app

# Install python and rasterstats dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-rasterio \
    python3-shapely \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install rasterstats

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 5000

CMD ["node", "server.js"]
